name: mqtt_broker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mqtt_client: ^10.2.0
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  get_it: ^7.6.7
  envied: ^0.5.3
  equatable: ^2.0.5
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  dartz: ^0.10.1
  device_preview: ^1.1.0
  package_info_plus: ^5.0.1
  connectivity_plus: ^2.3.8
  internet_connection_checker: ^1.0.0+1
  auto_route: ^7.8.4
  intl: ^0.18.1
  freezed: ^2.4.7

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  injectable_generator: ^2.4.2
  flutter_gen_runner: ^5.3.2
  envied_generator: ^0.5.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/generate/gen
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.otf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.otf
          weight: 100
